// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXjCzAmSkF14SEuci1AD1I9gFhMnixfak',
    appId: '1:1022324330096:web:983b89f6c8385f2d93aeb5',
    messagingSenderId: '1022324330096',
    projectId: 'cinetec-66c6c',
    authDomain: 'cinetec-66c6c.firebaseapp.com',
    storageBucket: 'cinetec-66c6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuYI8hrAta5fQRrTFgRCXA6ykVni88qRg',
    appId: '1:1022324330096:android:8d7891963ef42bdd93aeb5',
    messagingSenderId: '1022324330096',
    projectId: 'cinetec-66c6c',
    storageBucket: 'cinetec-66c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm7diXxijrssmLC3iIx6PsZo1EH-KIDUs',
    appId: '1:1022324330096:ios:447144a54aa7c48793aeb5',
    messagingSenderId: '1022324330096',
    projectId: 'cinetec-66c6c',
    storageBucket: 'cinetec-66c6c.firebasestorage.app',
    iosBundleId: 'com.example.projectSql',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm7diXxijrssmLC3iIx6PsZo1EH-KIDUs',
    appId: '1:1022324330096:ios:447144a54aa7c48793aeb5',
    messagingSenderId: '1022324330096',
    projectId: 'cinetec-66c6c',
    storageBucket: 'cinetec-66c6c.firebasestorage.app',
    iosBundleId: 'com.example.projectSql',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXjCzAmSkF14SEuci1AD1I9gFhMnixfak',
    appId: '1:1022324330096:web:3b21e10213d9b62193aeb5',
    messagingSenderId: '1022324330096',
    projectId: 'cinetec-66c6c',
    authDomain: 'cinetec-66c6c.firebaseapp.com',
    storageBucket: 'cinetec-66c6c.firebasestorage.app',
  );
}
